name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Runs the workflow when code is pushed to the main branch

jobs:
  build-and-push:
    # Use a standard, free, GitHub-hosted runner
    runs-on: ubuntu-latest
    
    # Permissions required to read source code and write to GHCR
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # The GITHUB_TOKEN is a temporary secret provided by GitHub for each workflow run
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=,suffix=,format={{sha}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Looks for the Dockerfile in the current directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}