name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Runs the workflow when code is pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # This should correctly evaluate to ghcr.io/omid-mosayebi/hello-world-java
          images: ghcr.io/${{ github.repository }} 
          
          # This is the corrected multi-line YAML structure
          tags: |
            # FIX: Use 'event=true' which tells the action to derive the SHA tag 
            # from the push event, avoiding the problematic 'format' syntax.
            type=sha,event=true
            # Keep the 'latest' tag line as well
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          
            
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
